const path = require('path');
const fs = require('fs');

function getLogoBase64() {
  try {
    const logoPath = path.resolve(__dirname, '../../frontend/public/logo.png');
    return `data:image/png;base64,${fs.readFileSync(logoPath).toString('base64')}`;
  } catch { return ''; }
}

function generateInvoiceHTML(invoice, lang = 'fr') {
  const logo = getLogoBase64();
  const l = lang === 'fr' ? {
    title: 'FACTURE', invoiceNo: 'Facture N°', issueDate: 'Date d\'émission',
    dueDate: 'Date d\'échéance', client: 'Client', amount: 'Montant',
    status: 'Statut', paid: 'Payée', pending: 'En attente', late: 'En retard',
    company: 'TAC-TIC', companyAddr: 'Tunisie',
    footer: 'Ce document est généré automatiquement par la plateforme Tac-Tic ERM.',
    subtotal: 'Sous-total', tva: 'TVA (19%)', total: 'Total TTC',
  } : {
    title: 'INVOICE', invoiceNo: 'Invoice No.', issueDate: 'Issue Date',
    dueDate: 'Due Date', client: 'Client', amount: 'Amount',
    status: 'Status', paid: 'Paid', pending: 'Pending', late: 'Late',
    company: 'TAC-TIC', companyAddr: 'Tunisia',
    footer: 'This document is auto-generated by the Tac-Tic ERM platform.',
    subtotal: 'Subtotal', tva: 'VAT (19%)', total: 'Total incl. VAT',
  };

  const statusText = l[invoice.status] || invoice.status;
  const statusColor = invoice.status === 'paid' ? '#0d9e6e' : invoice.status === 'late' ? '#ba1a1a' : '#d97706';
  const invNo = `INV-${String(invoice._id).slice(-6).toUpperCase()}`;
  const issueDate = new Date(invoice.issueDate || invoice.createdAt).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const dueDate = new Date(invoice.dueDate).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const subtotal = invoice.amount;
  const tva = subtotal * 0.19;
  const total = subtotal + tva;
  const fmtTND = (n) => n.toLocaleString('en-US', { minimumFractionDigits: 3, maximumFractionDigits: 3 }) + ' TND';

  return `<!DOCTYPE html>
<html lang="${lang}">
<head><meta charset="utf-8">
<style>
  @page { margin: 0; size: A4; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #191c1e; font-size: 11px; }
  .page { width: 210mm; min-height: 297mm; padding: 25mm; position: relative; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #00355f; }
  .company { }
  .company img { height: 32px; margin-bottom: 8px; }
  .company p { font-size: 9px; color: #57657a; }
  .inv-title { text-align: right; }
  .inv-title h1 { font-size: 28px; font-weight: 800; color: #00355f; letter-spacing: 3px; }
  .inv-title .inv-no { font-size: 12px; color: #57657a; margin-top: 4px; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 40px; }
  .meta-box { }
  .meta-label { font-size: 8px; color: #57657a; text-transform: uppercase; letter-spacing: 1.5px; font-weight: 700; margin-bottom: 6px; }
  .meta-value { font-size: 13px; font-weight: 700; color: #191c1e; }
  .meta-sub { font-size: 10px; color: #57657a; margin-top: 2px; }
  .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 10px; font-weight: 700; color: #fff; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
  th { background: #f0f2f4; color: #57657a; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; font-size: 8px; padding: 10px 14px; text-align: left; border-bottom: 2px solid #e8ecf1; }
  td { padding: 12px 14px; border-bottom: 1px solid #e8ecf1; font-size: 11px; }
  .text-right { text-align: right; }
  .total-row { background: #00355f; color: #fff; }
  .total-row td { font-weight: 800; font-size: 13px; border: none; padding: 14px; }
  .footer { position: absolute; bottom: 20mm; left: 25mm; right: 25mm; text-align: center; font-size: 8px; color: #8d99ae; border-top: 1px solid #e8ecf1; padding-top: 10px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="company">
      ${logo ? `<img src="${logo}" alt="Tac-Tic">` : '<strong>TAC-TIC</strong>'}
      <p>${l.companyAddr}</p>
    </div>
    <div class="inv-title">
      <h1>${l.title}</h1>
      <div class="inv-no">${l.invoiceNo} ${invNo}</div>
    </div>
  </div>

  <div class="meta">
    <div>
      <div class="meta-box">
        <div class="meta-label">${l.client}</div>
        <div class="meta-value">${invoice.clientName}</div>
      </div>
    </div>
    <div style="text-align:right">
      <div class="meta-box">
        <div class="meta-label">${l.issueDate}</div>
        <div class="meta-value">${issueDate}</div>
      </div>
      <div class="meta-box" style="margin-top:12px">
        <div class="meta-label">${l.dueDate}</div>
        <div class="meta-value">${dueDate}</div>
      </div>
      <div class="meta-box" style="margin-top:12px">
        <div class="meta-label">${l.status}</div>
        <span class="status-badge" style="background:${statusColor}">${statusText}</span>
      </div>
    </div>
  </div>

  ${invoice.reference ? `<div style="margin-bottom:20px"><div class="meta-label">${lang === 'fr' ? 'Référence' : 'Reference'}</div><div class="meta-value" style="font-size:11px">${invoice.reference}</div></div>` : ''}

  <table>
    <tr><th>Description</th><th class="text-right">${l.amount}</th></tr>
    <tr><td>${invoice.description || (lang === 'fr' ? 'Prestation de services' : 'Service delivery')} — ${invoice.clientName}</td><td class="text-right" style="font-weight:700">${fmtTND(subtotal)}</td></tr>
  </table>

  ${invoice.notes ? `<div style="margin-top:20px;padding:10px 14px;background:#f7f9fb;border-radius:6px;font-size:9px;color:#57657a"><strong>${lang === 'fr' ? 'Notes :' : 'Notes:'}</strong> ${invoice.notes}</div>` : ''}

  <table style="width:50%;margin-left:auto">
    <tr><td>${l.subtotal}</td><td class="text-right" style="font-weight:600">${fmtTND(subtotal)}</td></tr>
    <tr><td>${l.tva}</td><td class="text-right">${fmtTND(tva)}</td></tr>
    <tr class="total-row"><td>${l.total}</td><td class="text-right">${fmtTND(total)}</td></tr>
  </table>

  <div class="footer">${l.footer}</div>
</div>
</body></html>`;
}

module.exports = { generateInvoiceHTML };
