const path = require('path');
const fs = require('fs');

function getLogoBase64() {
  try {
    const logoPath = path.resolve(__dirname, '../../frontend/public/logo.png');
    return `data:image/png;base64,${fs.readFileSync(logoPath).toString('base64')}`;
  } catch { return ''; }
}

function generateTransactionHTML(tx, lang = 'fr') {
  const logo = getLogoBase64();
  const l = lang === 'fr' ? {
    title: 'REÇU DE TRANSACTION', type: 'Type', income: 'Revenu', expense: 'Dépense',
    amount: 'Montant', date: 'Date', category: 'Catégorie', description: 'Description',
    reference: 'Référence', paymentMethod: 'Mode de paiement', notes: 'Notes',
    company: 'TAC-TIC', addr: 'Tunisie',
    footer: 'Ce document est généré automatiquement par la plateforme Tac-Tic ERM.',
    methods: { virement: 'Virement bancaire', cheque: 'Chèque', especes: 'Espèces', carte: 'Carte bancaire', autre: 'Autre' },
  } : {
    title: 'TRANSACTION RECEIPT', type: 'Type', income: 'Income', expense: 'Expense',
    amount: 'Amount', date: 'Date', category: 'Category', description: 'Description',
    reference: 'Reference', paymentMethod: 'Payment Method', notes: 'Notes',
    company: 'TAC-TIC', addr: 'Tunisia',
    footer: 'This document is auto-generated by the Tac-Tic ERM platform.',
    methods: { virement: 'Bank transfer', cheque: 'Check', especes: 'Cash', carte: 'Credit card', autre: 'Other' },
  };

  const txDate = new Date(tx.date || tx.createdAt).toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const typeLabel = tx.type === 'income' ? l.income : l.expense;
  const typeColor = tx.type === 'income' ? '#0d9e6e' : '#ba1a1a';
  const fmtTND = (n) => n.toLocaleString('en-US', { minimumFractionDigits: 3, maximumFractionDigits: 3 }) + ' TND';
  const txNo = `TX-${String(tx._id).slice(-6).toUpperCase()}`;

  return `<!DOCTYPE html>
<html lang="${lang}">
<head><meta charset="utf-8">
<style>
  @page { margin: 0; size: A4; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #191c1e; font-size: 11px; }
  .page { width: 210mm; min-height: 297mm; padding: 25mm; position: relative; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #00355f; }
  .company img { height: 32px; margin-bottom: 8px; }
  .company p { font-size: 9px; color: #57657a; }
  .inv-title { text-align: right; }
  .inv-title h1 { font-size: 24px; font-weight: 800; color: #00355f; letter-spacing: 2px; }
  .inv-title .inv-no { font-size: 11px; color: #57657a; margin-top: 4px; }
  .meta-label { font-size: 8px; color: #57657a; text-transform: uppercase; letter-spacing: 1.5px; font-weight: 700; margin-bottom: 4px; }
  .meta-value { font-size: 13px; font-weight: 700; color: #191c1e; }
  .detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 30px; }
  .detail-box { padding: 16px; background: #f7f9fb; border-radius: 8px; }
  .amount-box { text-align: center; padding: 30px; background: #f7f9fb; border-radius: 8px; margin-bottom: 30px; }
  .amount-value { font-size: 32px; font-weight: 800; }
  .type-badge { display: inline-block; padding: 4px 14px; border-radius: 20px; font-size: 10px; font-weight: 700; color: #fff; margin-top: 8px; }
  .notes-box { padding: 12px 16px; background: #f7f9fb; border-radius: 8px; font-size: 10px; color: #57657a; margin-top: 20px; }
  .footer { position: absolute; bottom: 20mm; left: 25mm; right: 25mm; text-align: center; font-size: 8px; color: #8d99ae; border-top: 1px solid #e8ecf1; padding-top: 10px; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="company">
      ${logo ? `<img src="${logo}" alt="Tac-Tic">` : '<strong>TAC-TIC</strong>'}
      <p>${l.addr}</p>
    </div>
    <div class="inv-title">
      <h1>${l.title}</h1>
      <div class="inv-no">${txNo}</div>
    </div>
  </div>

  <!-- Amount hero -->
  <div class="amount-box">
    <div class="meta-label">${l.amount}</div>
    <div class="amount-value" style="color:${typeColor}">${fmtTND(tx.amount)}</div>
    <span class="type-badge" style="background:${typeColor}">${typeLabel}</span>
  </div>

  <!-- Details grid -->
  <div class="detail-grid">
    <div class="detail-box">
      <div class="meta-label">${l.date}</div>
      <div class="meta-value">${txDate}</div>
    </div>
    <div class="detail-box">
      <div class="meta-label">${l.category}</div>
      <div class="meta-value">${tx.category}</div>
    </div>
    ${tx.description ? `<div class="detail-box"><div class="meta-label">${l.description}</div><div class="meta-value" style="font-size:11px">${tx.description}</div></div>` : ''}
    ${tx.reference ? `<div class="detail-box"><div class="meta-label">${l.reference}</div><div class="meta-value" style="font-size:11px">${tx.reference}</div></div>` : ''}
    ${tx.paymentMethod ? `<div class="detail-box"><div class="meta-label">${l.paymentMethod}</div><div class="meta-value" style="font-size:11px">${l.methods[tx.paymentMethod] || tx.paymentMethod}</div></div>` : ''}
  </div>

  ${tx.notes ? `<div class="notes-box"><strong>${l.notes} :</strong> ${tx.notes}</div>` : ''}

  <div class="footer">${l.footer}</div>
</div>
</body></html>`;
}

module.exports = { generateTransactionHTML };
